spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wjf8882300/eureka-demo.git
          search-paths: config-repo
server:
  port: 1201

#对称加密  
#encrypt:
#  key: tongguxinxi

#非对称(RSA)
encrypt:
  key-store:
    location: config-server.keystore
    alias: config-server
    password: 123456
    secret: 123456