server:
  port: 8010
spring:
  application:
    name: eureka-feign-consumer
eureka:
  client:
    #表示是否将自己注册到Eureka Server上，默认为true，当前应用为Eureka Server所以无需注册
    registerWithEureka: false 
    serviceUrl:
      defaultZone: http://wangjf:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
feign:
  httpclient:
    enabled: false
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: false
   

 
 

      
 
       
                                                                                     
                                                         